// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/history.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/missions.tsx";
import * as $3 from "./routes/upcoming.tsx";
import * as $$0 from "./islands/LaunchHistory.tsx";
import * as $$1 from "./islands/LaunchTable.tsx";
import * as $$2 from "./islands/MissionLaunchForm.tsx";

const manifest = {
  routes: {
    "./routes/history.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/missions.tsx": $2,
    "./routes/upcoming.tsx": $3,
  },
  islands: {
    "./islands/LaunchHistory.tsx": $$0,
    "./islands/LaunchTable.tsx": $$1,
    "./islands/MissionLaunchForm.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
